export const client = {
  name: "Gardens by Peter Lloyd",
  tagline: "Professional Landscaper in Liverpool — Quality You Can Trust",
  description: "Professional landscaper services in Liverpool and surrounding areas. Trusted local experts with 13 Google reviews.",
  category: "Landscaper",
  yearEstablished: "2015",
  phone: "",
  email: "",
  website: "",
  address: "",
  city: "Liverpool",
  county: "",
  postcode: "",
  basedIn: "Liverpool",
  founderName: "Peter",
  founderSurname: "",
  founderRole: "Director",
  facebook: "",
  instagram: "",
  linkedin: "",
  twitter: "",
  googleRating: "5",
  reviewCount: "13",
  services: [
    { title: "Garden Design", description: "Bespoke garden designs tailored to your lifestyle and space.", icon: "tree" },
    { title: "Landscaping", description: "Complete hard and soft landscaping to transform your outdoor area.", icon: "shovel" },
    { title: "Paving & Patios", description: "Beautiful paving solutions using premium natural stone and porcelain.", icon: "wall" },
    { title: "Planting Schemes", description: "Year-round colour and interest with expertly curated planting plans.", icon: "flower" },
  ],
  cinematic: {
    frameCount: 181, frameDir: "/frames/", framePrefix: "frame_", frameExtension: ".jpg",
    framePadding: 4, scrollLength: "500vh", mobileFrameCount: 181, mobileFrameDir: "/frames-mobile/",
    scrubSpeed: 0.5, heroStillImage: "/images/hero-still.jpg", heroStillImageMobile: "/images/hero-still-mobile.jpg",
  },
  beforeAfter: { beforeImage: "/images/before.jpg", afterImage: "/images/after.jpg", beforeLabel: "Current Garden", afterLabel: "Our Vision" },
  transformations: [
    { before: "/images/before.jpg", after: "/images/after.jpg", label: "Complete Garden Renovation" },
    { before: "/images/patio-before.jpg", after: "/images/patio-after.jpg", label: "Patio & Fencing" },
    { before: "/images/front-before.jpg", after: "/images/front-after.jpg", label: "Front Garden" },
    { before: "/images/lawn-before.jpg", after: "/images/lawn-after.jpg", label: "Lawn Restoration" },
    { before: "/images/fence-before.jpg", after: "/images/fence-after.jpg", label: "New Fencing" },
    { before: "/images/deck-before.jpg", after: "/images/deck-after.jpg", label: "Decking & Furniture" },
    { before: "/images/path-before.jpg", after: "/images/path-after.jpg", label: "Garden Path" },
    { before: "/images/border-before.jpg", after: "/images/border-after.jpg", label: "Planting Borders" },
    { before: "/images/drive-before.jpg", after: "/images/drive-after.jpg", label: "Driveway" },
  ] as { before: string; after: string; label: string }[],
  reviews: [
    { name: "Conner Maidment", rating: 5, text: "I was recommended to Peter from several business owners so I knew he had a great reputation before I enquired about required work on my back garden of a property I had just moved into. Peter came around to look what needed doing and ask questions as to what I wanted. Everything I wanted doing was done with care and consideration, a proper top job and was carried out by his colleague, Harrison.  On the day of the job, Harrison came around and just cracked straight on with no hesitation. He did all of the work that was quoted for me with a high level of care and professionalism - a true credit to Peter.  Thank you for the work that has been done and I know who to call if/when I need more work in the future.", date: "4 days ago" },
    { name: "Diane Diane", rating: 5, text: "Peter and his team carried out hard landscaping and other work for us several times last Summer and Autumn in preparation for some new buildings. We are very satisfied with the results and have no hesitation in recommending Peter", date: "3 weeks ago" },
    { name: "Tinho da Cruz", rating: 5, text: "We are very pleased with the work that Peter Lloyd and his team have completed in our garden: a network of paths suitable for a wheelchair. My wife, a landscape architect, is very satisfied with Peter's understanding and sympathy with what she wanted to achieve. His worker Harrison was cheerful and professional at all times and did not complain once despite having to shift and install around fifty tons of material from the front to the back of the house. We have no hesitation in recommending Gardens by Peter Lloyd.", date: "2 months ago", badge: "Local Guide" },
    { name: "lisa-louise Bunting", rating: 5, text: "The Peace Garden in Liverpool’s Baltic Triangle, created and lovingly maintained by Gardens by Peter Lloyd, is truly a special place. Nestled within the busy city centre, it offers a beautiful and calming escape—a sanctuary of peace and reflection.  Peter's dedication to this garden goes far beyond simple landscaping. After the garden was sadly vandalised, Peter didn’t give up. Instead, he worked tirelessly to rebuild what was lost. He also raised funds to replace the damaged items, making sure the memory and meaning behind each feature, we're preserved. This included installing a bench dedicated to the memory of my late husband Anthony.  For our family, this space has become more than just a garden. It’s a place of comfort and remembrance where we regularly gather to celebrate Anthony’s short but impactful life. Sitting by his bench in the peaceful surroundings has become part of our healing journey.  Peter continues to organise volunteer clean-up days, bringing the community together to care for this beautiful space. His ongoing work makes the garden not only a place of nature but one of hope, connection, and kindness.  It’s rare to find such a thoughtful and tranquil area in the heart of a hectic city, and we are deeply grateful for everything Peter has done and continues to do.", date: "9 months ago" },
    { name: "Paula Denny", rating: 5, text: "We worked with Gardens by Peter Lloyd who supported us to design and create a sensory Garden at my nursery setting. I cannot recommend these guys enough. Peter fully understood the brief and what we were trying to achieve and designed the perfect space for use by the children and families who attend. His knowledge of horticulture and sustainability is just phenomenal and his passion for his work really shines through. Once we had designed the Garden together and were booked in for the project to start the work began. These guys arrived when they said they would and worked flat out until completion, with very limited disruption to the setting and the services we offer to families. Peter then provided us with an after care plan and has also provided aftercare by visiting the site to ensure everything is bedding in and coming to life. The sensory Garden is just beautiful and has provided a space that both children and families can enjoy. The garden provides a range of plants, flowers, trees, beautiful seating areas and even a wildflower meadow that stimulates all of the children's senses and attracts a range of wildlife into the garden for everyone to enjoy.  If you are looking to start a garden project big or small these are the guys to go to.", date: "9 months ago" },
    { name: "Etieno Enang", rating: 5, text: "Peter and his team are attentive to detail and extremely professional. I highly recommend them!", date: "a year ago" },
  ] as { name: string; rating: number; text: string; date: string; badge?: string }[],
  seo: {
    title: "Gardens by Peter Lloyd | Professional Landscaper in Liverpool",
    description: "Professional landscaper in Liverpool. 5 stars on Google with 13 reviews. Quality workmanship guaranteed.",
  },
};
